from bot import CMD_INDEX


class _BotCommands:
    def __init__(self):
        self.StartCommand = f'starttb32{CMD_INDEX}'
        self.MirrorCommand = f'mirrortb32{CMD_INDEX}'
        self.UnzipMirrorCommand = f'unzipmirrortb32{CMD_INDEX}'
        self.ZipMirrorCommand = f'zipmirrortb32{CMD_INDEX}'
        self.CancelMirror = f'canceltb32{CMD_INDEX}'
        self.CancelAllCommand = f'cancelalltb32{CMD_INDEX}'
        self.ListCommand = f'listtb32{CMD_INDEX}'
        self.SearchCommand = f'searchtb32{CMD_INDEX}'
        self.StatusCommand = f'statustb32{CMD_INDEX}'
        self.AuthorizedUsersCommand = f'userstb32{CMD_INDEX}'
        self.AuthorizeCommand = f'authorizetb32{CMD_INDEX}'
        self.UnAuthorizeCommand = f'unauthorizetb32{CMD_INDEX}'
        self.AddSudoCommand = f'addsudotb32{CMD_INDEX}'
        self.RmSudoCommand = f'rmsudotb32{CMD_INDEX}'
        self.PingCommand = f'pingtb32{CMD_INDEX}'
        self.RestartCommand = f'restarttb32{CMD_INDEX}'
        self.StatsCommand = f'statstb32{CMD_INDEX}'
        self.HelpCommand = f'helptb32{CMD_INDEX}'
        self.LogCommand = f'logtb32{CMD_INDEX}'
        self.SpeedCommand = f'speedtesttb32{CMD_INDEX}'
        self.CloneCommand = f'clonetb32{CMD_INDEX}'
        self.CountCommand = f'counttb32{CMD_INDEX}'
        self.WatchCommand = f'watchtb32{CMD_INDEX}'
        self.ZipWatchCommand = f'zipwatchtb32{CMD_INDEX}'
        self.QbMirrorCommand = f'qbmirrortb32{CMD_INDEX}'
        self.QbUnzipMirrorCommand = f'qbunzipmirrortb32{CMD_INDEX}'
        self.QbZipMirrorCommand = f'qbzipmirrortb32{CMD_INDEX}'
        self.DeleteCommand = f'deltb32{CMD_INDEX}'
        self.ShellCommand = f'shelltb32{CMD_INDEX}'
        self.ExecHelpCommand = f'exechelptb32{CMD_INDEX}'
        self.LeechSetCommand = f'leechsettb32{CMD_INDEX}'
        self.SetThumbCommand = f'setthumbtb32{CMD_INDEX}'
        self.LeechCommand = f'leechtb32{CMD_INDEX}'
        self.UnzipLeechCommand = f'unzipleechtb32{CMD_INDEX}'
        self.ZipLeechCommand = f'zipleechtb32{CMD_INDEX}'
        self.QbLeechCommand = f'qbleechtb32{CMD_INDEX}'
        self.QbUnzipLeechCommand = f'qbunzipleechtb32{CMD_INDEX}'
        self.QbZipLeechCommand = f'qbzipleechtb32{CMD_INDEX}'
        self.LeechWatchCommand = f'leechwatchtb32{CMD_INDEX}'
        self.LeechZipWatchCommand = f'leechzipwatchtb32{CMD_INDEX}'
        self.RssListCommand = f'rsslisttb32{CMD_INDEX}'
        self.RssGetCommand = f'rssgettb32{CMD_INDEX}'
        self.RssSubCommand = f'rsssubtb32{CMD_INDEX}'
        self.RssUnSubCommand = f'rssunsubtb32{CMD_INDEX}'
        self.RssSettingsCommand = f'rsssettb32{CMD_INDEX}'

BotCommands = _BotCommands()
